if: branch = master

dist: focal
sudo: required

git:
  depth: false

language: c++
os: linux
compiler:
  - gcc

addons:
  apt:
    packages:
    - valgrind
    - cmake
    - lcov
    - cppcheck
    - libgtest-dev
    - libgmock-dev

before_script:
  - cppcheck --inconclusive --suppressions-list=suppressions.txt --enable=all --language=c++ --error-exitcode=1 entities/


script:
  - cmake .
  - make || travis_terminate 1
  - valgrind --error-exitcode=1 --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med --track-origins=yes ./entities/test/entities_unit_tests || travis_terminate 1

after_script:
  - lcov --capture --directory ./entities/CMakeFiles/entities_lib.dir --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "coverage info didn't collect"